module.exports = [
  {
     "product_id":1,
     "product_name":"Apple Juice",
     "ptype":"Beverages",
     "description":"Apple Juice",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":2,
     "product_name":"Beer, bottle, pilsener, import",
     "ptype":"Beverages",
     "description":"Beer, bottle, pilsener, import",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":3,
     "product_name":"Beer, can",
     "ptype":"Beverages",
     "description":"Beer, can",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":4,
     "product_name":"Coffee",
     "ptype":"Beverages",
     "description":"Coffee",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":5,
     "product_name":"Milk",
     "ptype":"Beverages",
     "description":"Milk",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":6,
     "product_name":"Milk, organic",
     "ptype":"Beverages",
     "description":"Milk, organic",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":7,
     "product_name":"Orange Juice, not from concentrate",
     "ptype":"Beverages",
     "description":"Orange Juice, not from concentrate",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":8,
     "product_name":"Soda, bottle",
     "ptype":"Beverages",
     "description":"Soda, bottle",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":9,
     "product_name":"Soda, bottle (Coke product)",
     "ptype":"Beverages",
     "description":"Soda, bottle (Coke product)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":10,
     "product_name":"Soda, can",
     "ptype":"Beverages",
     "description":"Soda, can",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":11,
     "product_name":"Soda, can (Coke product)",
     "ptype":"Beverages",
     "description":"Soda, can (Coke product)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":12,
     "product_name":"Tea, green, bags",
     "ptype":"Beverages",
     "description":"Tea, green, bags",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":13,
     "product_name":"Water, regular/drinking",
     "ptype":"Beverages",
     "description":"Water, regular/drinking",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":14,
     "product_name":"Water, Sparkling/Mineral",
     "ptype":"Beverages",
     "description":"Water, Sparkling/Mineral",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":15,
     "product_name":"Wine, table, Cabernet",
     "ptype":"Beverages",
     "description":"Wine, table, Cabernet",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":16,
     "product_name":"Wine, table, Chardonnay",
     "ptype":"Beverages",
     "description":"Wine, table, Chardonnay",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":17,
     "product_name":"Wine, table, White Zinfandel",
     "ptype":"Beverages",
     "description":"Wine, table, White Zinfandel",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":18,
     "product_name":"Apple Sauce",
     "ptype":"Canned & Packaged Foods",
     "description":"Apple Sauce",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":19,
     "product_name":"Barbeque Sauce",
     "ptype":"Canned & Packaged Foods",
     "description":"Barbeque Sauce",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":20,
     "product_name":"Bread Crumbs",
     "ptype":"Canned & Packaged Foods",
     "description":"Bread Crumbs",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":21,
     "product_name":"Cheery Pie Filling",
     "ptype":"Canned & Packaged Foods",
     "description":"Cheery Pie Filling",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":22,
     "product_name":"Chicken Noodle Soup, condensed",
     "ptype":"Canned & Packaged Foods",
     "description":"Chicken Noodle Soup, condensed",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":23,
     "product_name":"Chicken Noodle Soup, regular",
     "ptype":"Canned & Packaged Foods",
     "description":"Chicken Noodle Soup, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":24,
     "product_name":"Chips, potato chips",
     "ptype":"Canned & Packaged Foods",
     "description":"Chips, potato chips",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":25,
     "product_name":"Coconut Milk",
     "ptype":"Canned & Packaged Foods",
     "description":"Coconut Milk",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":26,
     "product_name":"Flour, all purpose",
     "ptype":"Canned & Packaged Foods",
     "description":"Flour, all purpose",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":27,
     "product_name":"Flour, self rising",
     "ptype":"Canned & Packaged Foods",
     "description":"Flour, self rising",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":28,
     "product_name":"Green Beans, canned",
     "ptype":"Canned & Packaged Foods",
     "description":"Green Beans, canned",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":29,
     "product_name":"Honey",
     "ptype":"Canned & Packaged Foods",
     "description":"Honey",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":30,
     "product_name":"Jalopeño Peppers, canned",
     "ptype":"Canned & Packaged Foods",
     "description":"Jalopeño Peppers, canned",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":31,
     "product_name":"Ketchup",
     "ptype":"Canned & Packaged Foods",
     "description":"Ketchup",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":32,
     "product_name":"Mandarin Oranges, canned",
     "ptype":"Canned & Packaged Foods",
     "description":"Mandarin Oranges, canned",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":33,
     "product_name":"Mayonnaise",
     "ptype":"Canned & Packaged Foods",
     "description":"Mayonnaise",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":34,
     "product_name":"Milk Chocolate Bar",
     "ptype":"Canned & Packaged Foods",
     "description":"Milk Chocolate Bar",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":35,
     "product_name":"Mushrooms, stems/pieces",
     "ptype":"Canned & Packaged Foods",
     "description":"Mushrooms, stems/pieces",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":36,
     "product_name":"Mustard, dijon",
     "ptype":"Canned & Packaged Foods",
     "description":"Mustard, dijon",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":37,
     "product_name":"Mustard, yellow",
     "ptype":"Canned & Packaged Foods",
     "description":"Mustard, yellow",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":38,
     "product_name":"Nutella",
     "ptype":"Canned & Packaged Foods",
     "description":"Nutella",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":39,
     "product_name":"Oil, Canola, 100% pure",
     "ptype":"Canned & Packaged Foods",
     "description":"Oil, Canola, 100% pure",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":40,
     "product_name":"Oil, Olive, 100% pure",
     "ptype":"Canned & Packaged Foods",
     "description":"Oil, Olive, 100% pure",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":41,
     "product_name":"Oil, Olive, extra virgin",
     "ptype":"Canned & Packaged Foods",
     "description":"Oil, Olive, extra virgin",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":42,
     "product_name":"Pasta, Egg Noodles",
     "ptype":"Canned & Packaged Foods",
     "description":"Pasta, Egg Noodles",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":43,
     "product_name":"Pasta, Ellbow Maccaroni",
     "ptype":"Canned & Packaged Foods",
     "description":"Pasta, Ellbow Maccaroni",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":44,
     "product_name":"Pasta, Penne Rigate",
     "ptype":"Canned & Packaged Foods",
     "description":"Pasta, Penne Rigate",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":45,
     "product_name":"Pasta, Rotini/Rotelle/Fusilli",
     "ptype":"Canned & Packaged Foods",
     "description":"Pasta, Rotini/Rotelle/Fusilli",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":46,
     "product_name":"Pasta, Spaghetti",
     "ptype":"Canned & Packaged Foods",
     "description":"Pasta, Spaghetti",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":47,
     "product_name":"Peanut Butter",
     "ptype":"Canned & Packaged Foods",
     "description":"Peanut Butter",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":48,
     "product_name":"Peanuts, roasted",
     "ptype":"Canned & Packaged Foods",
     "description":"Peanuts, roasted",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":49,
     "product_name":"Pepper, black, ground",
     "ptype":"Canned & Packaged Foods",
     "description":"Pepper, black, ground",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":50,
     "product_name":"Preserves",
     "ptype":"Canned & Packaged Foods",
     "description":"Preserves",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":51,
     "product_name":"Pretzels",
     "ptype":"Canned & Packaged Foods",
     "description":"Pretzels",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":52,
     "product_name":"Rice, instant, white",
     "ptype":"Canned & Packaged Foods",
     "description":"Rice, instant, white",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":53,
     "product_name":"Rice, regular",
     "ptype":"Canned & Packaged Foods",
     "description":"Rice, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":54,
     "product_name":"Salad Dressing",
     "ptype":"Canned & Packaged Foods",
     "description":"Salad Dressing",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":55,
     "product_name":"Salsa, medium hot",
     "ptype":"Canned & Packaged Foods",
     "description":"Salsa, medium hot",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":56,
     "product_name":"Salt",
     "ptype":"Canned & Packaged Foods",
     "description":"Salt",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":57,
     "product_name":"Soup, organic",
     "ptype":"Canned & Packaged Foods",
     "description":"Soup, organic",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":58,
     "product_name":"Spaghetti Sauce",
     "ptype":"Canned & Packaged Foods",
     "description":"Spaghetti Sauce",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":59,
     "product_name":"Sugar, brown",
     "ptype":"Canned & Packaged Foods",
     "description":"Sugar, brown",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":60,
     "product_name":"Sugar, powdered",
     "ptype":"Canned & Packaged Foods",
     "description":"Sugar, powdered",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":61,
     "product_name":"Sugar, white",
     "ptype":"Canned & Packaged Foods",
     "description":"Sugar, white",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":62,
     "product_name":"Syrup, breakfast",
     "ptype":"Canned & Packaged Foods",
     "description":"Syrup, breakfast",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":63,
     "product_name":"Tomato Paste",
     "ptype":"Canned & Packaged Foods",
     "description":"Tomato Paste",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":64,
     "product_name":"Tomato Sauce",
     "ptype":"Canned & Packaged Foods",
     "description":"Tomato Sauce",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":65,
     "product_name":"Tomato Soup, condensed",
     "ptype":"Canned & Packaged Foods",
     "description":"Tomato Soup, condensed",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":66,
     "product_name":"Tomato Soup, regular",
     "ptype":"Canned & Packaged Foods",
     "description":"Tomato Soup, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":67,
     "product_name":"Tuna, chunky, in water",
     "ptype":"Canned & Packaged Foods",
     "description":"Tuna, chunky, in water",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":68,
     "product_name":"Tuna, solid, in water",
     "ptype":"Canned & Packaged Foods",
     "description":"Tuna, solid, in water",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":69,
     "product_name":"Vanilla Extract, pure",
     "ptype":"Canned & Packaged Foods",
     "description":"Vanilla Extract, pure",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":70,
     "product_name":"Bagles, plain",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Bagles, plain",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":71,
     "product_name":"Baguette/French Bread",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Baguette/French Bread",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":72,
     "product_name":"Bread, 12 grain",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Bread, 12 grain",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":73,
     "product_name":"Cereal, Müsli style",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Cereal, Müsli style",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":74,
     "product_name":"Cocoa Rice Cereal",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Cocoa Rice Cereal",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":75,
     "product_name":"Corn Flakes, regular",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Corn Flakes, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":76,
     "product_name":"Corn Flakes, sugar frosted",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Corn Flakes, sugar frosted",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":77,
     "product_name":"Croissants",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Croissants",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":78,
     "product_name":"Granola Bars, high fiber",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Granola Bars, high fiber",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":79,
     "product_name":"Granola Bars, regular",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Granola Bars, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":80,
     "product_name":"Honey Crunch Oats",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Honey Crunch Oats",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":81,
     "product_name":"Hot Dog Buns",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Hot Dog Buns",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":82,
     "product_name":"Oat Meal",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"Oat Meal",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":83,
     "product_name":"White Bread/Toast, enriched",
     "ptype":"Bakery, Breakfast, Cereal",
     "description":"White Bread/Toast, enriched",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":84,
     "product_name":"Breakfast Sausage, frozen",
     "ptype":"Frozen Foods",
     "description":"Breakfast Sausage, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":85,
     "product_name":"Chicken Breasts, frozen",
     "ptype":"Frozen Foods",
     "description":"Chicken Breasts, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":86,
     "product_name":"Chicken Nuggets, frozen",
     "ptype":"Frozen Foods",
     "description":"Chicken Nuggets, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":87,
     "product_name":"Chicken Tenderloins, frozen",
     "ptype":"Frozen Foods",
     "description":"Chicken Tenderloins, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":88,
     "product_name":"Fish, Flounder, frozen",
     "ptype":"Frozen Foods",
     "description":"Fish, Flounder, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":89,
     "product_name":"Fish, Mahi Mahi, frozen",
     "ptype":"Frozen Foods",
     "description":"Fish, Mahi Mahi, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":90,
     "product_name":"Fish, Tilapia, frozen",
     "ptype":"Frozen Foods",
     "description":"Fish, Tilapia, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":91,
     "product_name":"French Fries, frozen",
     "ptype":"Frozen Foods",
     "description":"French Fries, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":92,
     "product_name":"Fruit, frozen",
     "ptype":"Frozen Foods",
     "description":"Fruit, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":93,
     "product_name":"Ground Beef, frozen",
     "ptype":"Frozen Foods",
     "description":"Ground Beef, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":94,
     "product_name":"Ground Turkey, frozen",
     "ptype":"Frozen Foods",
     "description":"Ground Turkey, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":95,
     "product_name":"Ice Cream, premium",
     "ptype":"Frozen Foods",
     "description":"Ice Cream, premium",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":96,
     "product_name":"Ice Cream, simple",
     "ptype":"Frozen Foods",
     "description":"Ice Cream, simple",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":97,
     "product_name":"Pizza, frozen (premium)",
     "ptype":"Frozen Foods",
     "description":"Pizza, frozen (premium)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":98,
     "product_name":"Pizza, frozen (simple)",
     "ptype":"Frozen Foods",
     "description":"Pizza, frozen (simple)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":99,
     "product_name":"Veggies, frozen",
     "ptype":"Frozen Foods",
     "description":"Veggies, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":100,
     "product_name":"Waffles, frozen",
     "ptype":"Frozen Foods",
     "description":"Waffles, frozen",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":101,
     "product_name":"Aluminum Foil",
     "ptype":"Miscellaneous Kitchen Items",
     "description":"Aluminum Foil",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":102,
     "product_name":"Paper Towles",
     "ptype":"Miscellaneous Kitchen Items",
     "description":"Paper Towles",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":103,
     "product_name":"Plastic Wrap",
     "ptype":"Miscellaneous Kitchen Items",
     "description":"Plastic Wrap",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":104,
     "product_name":"Apples, Gala, bag",
     "ptype":"Produce",
     "description":"Apples, Gala, bag",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":105,
     "product_name":"Apples, Red/Golden Delicious, bag",
     "ptype":"Produce",
     "description":"Apples, Red/Golden Delicious, bag",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":106,
     "product_name":"Carrots, whole",
     "ptype":"Produce",
     "description":"Carrots, whole",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":107,
     "product_name":"Grapes, red",
     "ptype":"Produce",
     "description":"Grapes, red",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":108,
     "product_name":"Lemons",
     "ptype":"Produce",
     "description":"Lemons",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":109,
     "product_name":"Lettuce, iceberg",
     "ptype":"Produce",
     "description":"Lettuce, iceberg",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":110,
     "product_name":"Mushrooms, whole",
     "ptype":"Produce",
     "description":"Mushrooms, whole",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":111,
     "product_name":"Onions, yellow",
     "ptype":"Produce",
     "description":"Onions, yellow",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":112,
     "product_name":"Oranges",
     "ptype":"Produce",
     "description":"Oranges",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":113,
     "product_name":"Pears",
     "ptype":"Produce",
     "description":"Pears",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":114,
     "product_name":"Potatoes, gold (Yukon)",
     "ptype":"Produce",
     "description":"Potatoes, gold (Yukon)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":115,
     "product_name":"Potatoes, red",
     "ptype":"Produce",
     "description":"Potatoes, red",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":116,
     "product_name":"Potatoes, Russet",
     "ptype":"Produce",
     "description":"Potatoes, Russet",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":117,
     "product_name":"Tomatoes",
     "ptype":"Produce",
     "description":"Tomatoes",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":118,
     "product_name":"Bacon",
     "ptype":"Refrigerated Foods",
     "description":"Bacon",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":119,
     "product_name":"Beef Stew Meat",
     "ptype":"Refrigerated Foods",
     "description":"Beef Stew Meat",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":120,
     "product_name":"Brats, 4-6 pack",
     "ptype":"Refrigerated Foods",
     "description":"Brats, 4-6 pack",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":121,
     "product_name":"Butter, real, unsalted/salted",
     "ptype":"Refrigerated Foods",
     "description":"Butter, real, unsalted/salted",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":122,
     "product_name":"Cheese Singles (imitation)",
     "ptype":"Refrigerated Foods",
     "description":"Cheese Singles (imitation)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":123,
     "product_name":"Cheese, block (regular)",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, block (regular)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":124,
     "product_name":"Cheese, Boursin",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, Boursin",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":125,
     "product_name":"Cheese, Brie",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, Brie",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":126,
     "product_name":"Cheese, shredded, Mexican style",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, shredded, Mexican style",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":127,
     "product_name":"Cheese, shredded, Mozarella",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, shredded, Mozarella",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":128,
     "product_name":"Cheese, sliced, deli",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, sliced, deli",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":129,
     "product_name":"Cheese, sliced, regular",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, sliced, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":130,
     "product_name":"Cheese, wedge (real, deli)",
     "ptype":"Refrigerated Foods",
     "description":"Cheese, wedge (real, deli)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":131,
     "product_name":"Chocolate Chip Cookie Dough",
     "ptype":"Refrigerated Foods",
     "description":"Chocolate Chip Cookie Dough",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":132,
     "product_name":"Cold Cuts, ham or chicken",
     "ptype":"Refrigerated Foods",
     "description":"Cold Cuts, ham or chicken",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":133,
     "product_name":"Cold Cuts, turkey variety",
     "ptype":"Refrigerated Foods",
     "description":"Cold Cuts, turkey variety",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":134,
     "product_name":"Cottage Cheese",
     "ptype":"Refrigerated Foods",
     "description":"Cottage Cheese",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":135,
     "product_name":"Cream Cheese",
     "ptype":"Refrigerated Foods",
     "description":"Cream Cheese",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":136,
     "product_name":"Cream, heavy whipping",
     "ptype":"Refrigerated Foods",
     "description":"Cream, heavy whipping",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":137,
     "product_name":"Eggs, cage free",
     "ptype":"Refrigerated Foods",
     "description":"Eggs, cage free",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":138,
     "product_name":"Eggs, regular",
     "ptype":"Refrigerated Foods",
     "description":"Eggs, regular",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":139,
     "product_name":"Ground Beef (chuck), fresh",
     "ptype":"Refrigerated Foods",
     "description":"Ground Beef (chuck), fresh",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":140,
     "product_name":"Ground Beef (sirloin), fresh",
     "ptype":"Refrigerated Foods",
     "description":"Ground Beef (sirloin), fresh",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":141,
     "product_name":"Ground Turkey, fresh",
     "ptype":"Refrigerated Foods",
     "description":"Ground Turkey, fresh",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":142,
     "product_name":"Ham, half",
     "ptype":"Refrigerated Foods",
     "description":"Ham, half",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":143,
     "product_name":"Kielbasa",
     "ptype":"Refrigerated Foods",
     "description":"Kielbasa",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":144,
     "product_name":"Margarine/Spread",
     "ptype":"Refrigerated Foods",
     "description":"Margarine/Spread",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":145,
     "product_name":"Pancetta, diced",
     "ptype":"Refrigerated Foods",
     "description":"Pancetta, diced",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":146,
     "product_name":"Pizza Dough",
     "ptype":"Refrigerated Foods",
     "description":"Pizza Dough",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":147,
     "product_name":"Pork Tenderloin, small",
     "ptype":"Refrigerated Foods",
     "description":"Pork Tenderloin, small",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":148,
     "product_name":"Ribs, Baby Back (pork, unseasoned)",
     "ptype":"Refrigerated Foods",
     "description":"Ribs, Baby Back (pork, unseasoned)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":149,
     "product_name":"Ribs, Spare Back (pork, unseasoned)",
     "ptype":"Refrigerated Foods",
     "description":"Ribs, Spare Back (pork, unseasoned)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":150,
     "product_name":"Salami, sliced",
     "ptype":"Refrigerated Foods",
     "description":"Salami, sliced",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":151,
     "product_name":"Salami, whole",
     "ptype":"Refrigerated Foods",
     "description":"Salami, whole",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":152,
     "product_name":"Sour Cream",
     "ptype":"Refrigerated Foods",
     "description":"Sour Cream",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":153,
     "product_name":"Yoghurt, Dannon (etc.)",
     "ptype":"Refrigerated Foods",
     "description":"Yoghurt, Dannon (etc.)",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":154,
     "product_name":"Yogurt, Fage, 2%, plain",
     "ptype":"Refrigerated Foods",
     "description":"Yogurt, Fage, 2%, plain",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":155,
     "product_name":"Yogurt, Fage, w/ flavor",
     "ptype":"Refrigerated Foods",
     "description":"Yogurt, Fage, w/ flavor",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":156,
     "product_name":"Yogurt, flavored, cup",
     "ptype":"Refrigerated Foods",
     "description":"Yogurt, flavored, cup",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":157,
     "product_name":"Yogurt, greek style, plain",
     "ptype":"Refrigerated Foods",
     "description":"Yogurt, greek style, plain",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  },
  {
     "product_id":158,
     "product_name":"Yogurt, plain",
     "ptype":"Refrigerated Foods",
     "description":"Yogurt, plain",
     "price":1.0,
     "quantity_available":10,
     "icon_url":null,
     "image_url":null,
     "brand":null
  }
]